//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Ogrenci
{
    public string TC { get; set; }
    public string Ad { get; set; }
    public string Soyad { get; set; }
    public int Aldigi_ders_sayisi { get; set; }
    public decimal not_ortalamasi { get; set; }
}

public partial class students
{
    public int Student_No { get; set; }
    public string Name { get; set; }
    public Nullable<int> Age { get; set; }
    public string Course { get; set; }
    public Nullable<int> Marks { get; set; }
}
